### ISSUE TITLE
nothing run :/

### ISSUE THREAD

**Issue by Fr-Dae** [0x796935/factorio-achievement-restore#9]
Lubuntu 22.04
```shell
dae@dae-rog-gl753vd:~/Téléchargements/factorio-achievement-restore-main$ npm start

> start
> node packer.mjs

file:///home/dae/T%C3%A9l%C3%A9chargements/factorio-achievement-restore-main/packer.mjs:228
      if(offsetArray?.length > 0){
                     ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```
```
dae@dae-rog-gl753vd:~/Téléchargements/factorio-achievement-restore-main$ npm -v
8.5.1
dae@dae-rog-gl753vd:~/Téléchargements/factorio-achievement-restore-main$ nodejs -v
v12.22.9

```

**Comment by louanfontenele** [comment]
Use the latest Node version

![image](https://github.com/user-attachments/assets/1fd24796-9cfb-4679-b28b-33839e2d1759)

**Comment by Fr-Dae** [comment]
> Use the latest Node version
> 
> ![image](https://private-user-images.githubusercontent.com/2886066/392662481-1fd24796-9cfb-4679-b28b-33839e2d1759.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzkzNDIsIm5iZiI6MTczMzQ3OTA0MiwicGF0aCI6Ii8yODg2MDY2LzM5MjY2MjQ4MS0xZmQyNDc5Ni05Y2ZiLTQ2NzktYjI4Yi0zMzgzOWUyZDE3NTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDZUMDk1NzIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2IyZDdlODYwZmNlZTMzYmRhZmMzYTJmZjVhZjFhZWM0MjE0MjI1YzQ0ZDhhNjljODNhNTM2NzQxZDM2MjY5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.VFJeQMMzZlzhDBcVzIcdJ9-DuxeDTL93U_nICb49F8k)

```
dae@dae-rog-gl753vd:~$ node -v
v12.22.9
dae@dae-rog-gl753vd:~$ npm -v
8.5.1
```

oups
